server:
  port: 8091
spring:
  application:
    name: foto
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/foto
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
security:
  oauth2:
    client:
      clientId: perfil
      clientSecret: perfil123
    resource:
      loadBalanced: true
      userInfoUri: http://servidorautenticacao/validar
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
